package com.fatec.cadastrar;

// Generated by Selenium IDE
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class REQ01CadastrarLivroTSTests {
    private WebDriver driver;
    @Test
    public void ct01cadastrodelivrocomsucesso() {
        System.setProperty("webdriver.chrome.driver", "browserDriver/chromedriver.exe");
        driver = new ChromeDriver();
        driver.get("http://localhost:8080/livros/cadastrar");
        driver.findElement(By.id("isbn")).sendKeys("1111");
        driver.findElement(By.id("autor")).sendKeys("Pressman");
        driver.findElement(By.id("titulo")).sendKeys("Engenharia de Software");
        driver.findElement(By.cssSelector("//input[contains(@id,'cadastrarLivro')]")).click();
        assertEquals("Livro cadastrado", driver.findElement(By.cssSelector(".text-danger")).getText());
        driver.quit();
    }
}